[project]
name = "alphafold3-pytorch"
version = "0.0.54"
description = "AlphaFold 3 - Pytorch"
authors = [
    { name = "Phil Wang", email = "lucidrains@gmail.com" }
]
readme = "README.md"
requires-python = ">= 3.8"
license = { file = "LICENSE" }
keywords = [
    'artificial intelligence',
    'deep learning',
    'protein structure prediction',
]

classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
]

dependencies = [
    # --------- pytorch --------- #
    "torch>=2.1",
    "torchvision>=0.15.0",
    "lightning>=2.2.5",
    "torchmetrics>=0.11.4",
    "taylor-series-linear-attention>=0.1.9",

    # --------- hydra --------- #
    "hydra-core==1.3.2",
    "hydra-colorlog==1.2.0",
    "hydra-optuna-sweeper==1.2.0",

    # --------- loggers --------- #
    # "wandb",
    # "neptune-client",
    # "mlflow",
    # "comet-ml",
    # "aim>=3.16.2",  # no lower than 3.16.2, see https://github.com/aimhubio/aim/issues/2550

    # --------- others --------- #
    "einx>=0.2.2",     # for Einstein-inspired notation
    "einops>=0.8.0",   # for Einstein-inspired operations
    "jaxtyping>=0.2.28",  # tensor type checking
    "rootutils",       # standardizing the project root setup
    "pre-commit",      # hooks for applying linters on commit
    "rich",            # beautiful text formatting in terminal
    "pytest",          # tests
    "beartype",        # runtime type checking
    "tqdm",            # progress bars
    "setuptools",      # for packaging
    # "sh"            # for running bash commands in some tests (linux/macos only)
]

[project.urls]
Homepage = "https://pypi.org/project/alphafold3-pytorch/"
Repository = "https://github.com/lucidrains/alphafold3-pytorch"

[project.optional-dependencies]
examples = []
test = [
    "pytest"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
addopts = [
  "--color=yes",
  "--durations=0",
  "--strict-markers",
  "--doctest-modules",
]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
]
log_cli = "True"
markers = [
  "slow: slow tests",
]
minversion = "6.0"
testpaths = "tests/"

[tool.ruff]
line-length = 1000
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F", "I"] # <-- Note: I suggest including the "I" for additional checks!
ignore = [
  "E402",
  "F401",
  "F722", # Ignore Jaxtyping forward references: https://github.com/google/jaxtyping/blob/v0.2.12/FAQ.md
  "F821",
]

# Assuming you're developing for Python 3.10
target-version = "py310"

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | .env
  | venv
  | .venv
)/
'''
line-length = 99
target-version = ["py310"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["alphafold3-pytorch"]

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
